server:
  port: 9010

spring:
  application:
    name: "notification-service"
  cloud:
    function:
      definition: sendOrderCreatedEmail
    stream:
      bindings:
        sendOrderCreatedEmail-in-0:
          destination: send-order-created-email
          group: ${spring.application.name}
      kafka:
        binder:
          brokers:
            - localhost:9092
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username:
    password:
    protocol: smtp
    test-connection: false
    properties:
      mail:
       smtp:
        auth: true
        starttls:
         enable: true


