services:
  base-config:
    environment:
      SPRING_PROFILES_ACTIVE: qa
    networks:
      - keeb-store-net
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-base-config:
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    extends:
      service: base-config
    