server:
  port: 8082

spring:
  application:
    name: "user-service"
  data:
    mongodb:
      host: "keebMongoDB"
      port: 27017
      database: "User"
#  config:
#    import: "configserver:http://localhost:8071/"
#  profiles:
#    active: "dev"

management:
  endpoints:
    web:
      exposure:
        include: "*"
