server:
  port: 8084

spring:
  application:
    name: "order-service"
  data:
    mongodb:
      host: "keebMongoDB"
      port: 27017
      database: "Order"
#  config:
#    import: "configserver:http://localhost:8071/"
#    profiles:
#      active: "dev"

management:
  endpoints:
    web:
      exposure:
        include: "*"


