server:
  port: 8084

spring:
  application:
    name: "order-service"
  data:
    mongodb:
      host: "keebMongoDB"
      port: 27017
      database: "Order"
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: "dev"
  cloud:
    stream:
      bindings:
        sendOrderCreatedEmail-out-0:
          destination: send-order-created-email
      kafka:
        binder:
          brokers:
            - localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: "true"
  client:
    fetchRegistry: "true"
    registerWithEureka: "true"
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

info:
  app:
    name: "order-service"
    description: "order-service for keeb-store application"
    version: "1.0.0"
