services:
  microservice-base-config:
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
    depends_on:
      config-server:
        condition: service_healthy      
    networks:
      - keeb-store-net
    deploy:
      resources:
        limits:
          memory: 700m