services:
  keebDB:
    container_name: keebDatabase
    image: mysql
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: keebDatabase
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    networks:
      - keeb-store-net
      
  keebMongoDB:
    image: mongo:latest
    container_name: "keebMongoDB"
    ports:
      - 27017:27017
    networks:
      - keeb-store-net
      
  config-server:
    image: 'adityamankar/config-server:v1'
    container_name: config-server
    ports:
      - '8071:8071'
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s    
    extends:
      file: common-config.yml
      service: base-config
          
  eureka-server:
    image: 'adityamankar/eureka-server:v1'
    container_name: eureka-server
    ports:
      - '8070:8070'
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
    depends_on:
      config-server:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: base-config
      
  api-gateway:
    image: 'adityamankar/api-gateway:v1'
    container_name: api-gateway
    ports:
      - '8072:8072'
    environment:
      SPRING_APPLICATION_NAME: "api-gateway"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
    extends:
      file: common-config.yml
      service: microservice-base-config  

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    container_name: keycloak
    ports:
      - "7081:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    extends:
      file: common-config.yml
      service: base-config
   
  kafka:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - keeb-store-net

  inventory-service:
    image: 'adityamankar/inventory-service:v1'
    container_name: inventory-service-ms
    environment:
      SPRING_APPLICATION_NAME: "inventory-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://keebDatabase:3306/keebDatabase"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      keebDB:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config
      
  user-service:
    image: 'adityamankar/user-service:v1'
    container_name: user-service-ms
    extends:
      file: common-config.yml
      service: microservice-base-config    
  
  order-service:
    image: 'adityamankar/order-service:v1'
    container_name: order-service-ms
    environment:
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "kafka:9092"
    extends:
      file: common-config.yml
      service: microservice-base-config
          
  product-service:
    image: 'adityamankar/product-service:v1'
    container_name: product-service-ms
    environment:
      SPRING_APPLICATION_NAME: "product-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://keebDatabase:3306/keebDatabase"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      keebDB:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config
  
  notification-service:
    image: 'adityamankar/notification-service:v1'
    container_name: notification-service-ms
    environment:
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "kafka:9092"
    networks:
      - keeb-store-net
  

      
networks:
  keeb-store-net:
    driver: "bridge"
    
volumes:
  kafka_data:
    driver: local
