server:
  port: 8081

spring:
  application:
    name: "inventory-service"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3307/keebDB"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: "update"
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: "dev"

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: "true"
  client:
    fetchRegistry: "true"
    registerWithEureka: "true"
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

info:
  app:
    name: "inventory-service"
    description: "inventory-service for keeb-store application"
    version: "1.0.0"

